//! JavaScript code emitter
//!
//! Converts IR to readable JavaScript code.

use crate::ir::*;
use std::fmt::Write;

/// Sanitize a string to be a valid JavaScript identifier
fn sanitize_js_identifier(name: &str) -> String {
    let mut result = String::with_capacity(name.len());
    let mut chars = name.chars().peekable();

    // First character must be letter, underscore, or $
    if let Some(&c) = chars.peek() {
        if c.is_ascii_digit() {
            result.push('_');
        }
    }

    for c in chars {
        if c.is_ascii_alphanumeric() || c == '_' || c == '$' {
            result.push(c);
        } else {
            // Replace invalid characters with underscore
            // Collapse multiple underscores
            if !result.ends_with('_') {
                result.push('_');
            }
        }
    }

    // Remove trailing underscore
    while result.ends_with('_') && result.len() > 1 {
        result.pop();
    }

    // Handle empty result
    if result.is_empty() {
        return "func".to_string();
    }

    result
}

/// JavaScript emitter configuration
pub struct JsEmitter {
    /// Indentation string (spaces or tabs)
    indent: String,
    /// Current indentation level
    level: usize,
    /// Output buffer
    output: String,
    /// Module being emitted
    module: Option<Module>,
    /// Current function's parameter count (for local variable naming)
    current_param_count: usize,
    /// True when emitting in a boolean context (conditions)
    in_bool_context: bool,
}

impl JsEmitter {
    pub fn new() -> Self {
        Self {
            indent: "  ".to_string(),
            level: 0,
            output: String::new(),
            module: None,
            current_param_count: 0,
            in_bool_context: false,
        }
    }

    /// Emit a module to JavaScript
    pub fn emit(&mut self, module: &Module) -> String {
        self.module = Some(module.clone());
        self.output.clear();

        // Emit header comment
        self.emit_line("// Generated by wasm-decompile");
        self.emit_line("// https://github.com/anthropics/wasm-decompile");
        self.emit_line("");

        // Emit runtime helpers
        self.emit_runtime();
        self.emit_line("");

        // Emit data segments into memory
        if !module.data_segments.is_empty() {
            self.emit_line("// Data segments");
            self.emit_line("(function initMemory() {");
            self.level += 1;
            self.emit_line("const buf = new Uint8Array(memory.buffer);");
            for seg in &module.data_segments {
                if seg.data.is_empty() {
                    continue;
                }
                self.emit_data_segment(seg);
            }
            self.level -= 1;
            self.emit_line("})();");
            self.emit_line("");
        }

        // Emit imported function stubs
        let imported_funcs: Vec<&Function> =
            module.functions.iter().filter(|f| f.is_import).collect();
        if !imported_funcs.is_empty() {
            self.emit_line("// Imported functions (provide implementations to override stubs)");
            self.emit_line("const imports = {};");
            for func in &imported_funcs {
                let name = self.get_func_name(func.index);
                self.emit_line(&format!(
                    "function {}() {{ if (imports.{}) return imports.{}(...arguments); }}",
                    name, name, name
                ));
            }
            self.emit_line("");
        }

        // Emit globals
        if !module.globals.is_empty() {
            self.emit_line("// Globals");
            self.emit_line("const globals = {");
            self.level += 1;
            for (i, global) in module.globals.iter().enumerate() {
                let init = self.emit_expr(&global.init);
                self.emit_line(&format!("g{}: {},", i, init));
            }
            self.level -= 1;
            self.emit_line("};");
            // Create convenient accessors
            for (i, _) in module.globals.iter().enumerate() {
                self.emit_line(&format!(
                    "let g{i} = globals.g{i}; Object.defineProperty(globals, 'g{i}', {{ get() {{ return g{i}; }}, set(v) {{ g{i} = v; }} }});",
                    i = i
                ));
            }
            self.emit_line("");
        }

        // Emit functions
        for func in &module.functions {
            if !func.is_import {
                self.emit_function(func);
                self.emit_line("");
            }
        }

        // Emit function table (for call_indirect)
        if !module.elements.is_empty() {
            self.emit_function_table(module);
            self.emit_line("");
        }

        // Emit exports object
        self.emit_exports(module);

        std::mem::take(&mut self.output)
    }

    fn emit_runtime(&mut self) {
        self.emit_line("// @ts-nocheck");
        self.emit_line("// Runtime");
        let pages = self.module.as_ref().map(|m| m.memory_pages).unwrap_or(256);
        self.emit_line(&format!(
            "const memory = new WebAssembly.Memory({{ initial: {} }});",
            pages
        ));
        self.emit_line("let _mem_buf = memory.buffer, _mem_dv = new DataView(_mem_buf);");
        self.emit_line("function mem() { if (_mem_buf !== memory.buffer) { _mem_buf = memory.buffer; _mem_dv = new DataView(_mem_buf); } return _mem_dv; }");
        self.emit_line("");
        self.emit_line("// Memory helpers");
        self.emit_line(
            "function load_i32(addr, offset = 0) { return mem().getInt32(addr + offset, true); }",
        );
        self.emit_line(
            "function load_i64(addr, offset = 0) { return mem().getBigInt64(addr + offset, true); }",
        );
        self.emit_line(
            "function load_f32(addr, offset = 0) { return mem().getFloat32(addr + offset, true); }",
        );
        self.emit_line(
            "function load_f64(addr, offset = 0) { return mem().getFloat64(addr + offset, true); }",
        );
        self.emit_line(
            "function load_i8(addr, offset = 0) { return mem().getInt8(addr + offset); }",
        );
        self.emit_line(
            "function load_u8(addr, offset = 0) { return mem().getUint8(addr + offset); }",
        );
        self.emit_line(
            "function load_i16(addr, offset = 0) { return mem().getInt16(addr + offset, true); }",
        );
        self.emit_line(
            "function load_u16(addr, offset = 0) { return mem().getUint16(addr + offset, true); }",
        );
        self.emit_line("");
        self.emit_line("function store_i32(addr, value, offset = 0) { mem().setInt32(addr + offset, value, true); }");
        self.emit_line("function store_i64(addr, value, offset = 0) { mem().setBigInt64(addr + offset, value, true); }");
        self.emit_line("function store_f32(addr, value, offset = 0) { mem().setFloat32(addr + offset, value, true); }");
        self.emit_line("function store_f64(addr, value, offset = 0) { mem().setFloat64(addr + offset, value, true); }");
        self.emit_line(
            "function store_i8(addr, value, offset = 0) { mem().setInt8(addr + offset, value); }",
        );
        self.emit_line("function store_i16(addr, value, offset = 0) { mem().setInt16(addr + offset, value, true); }");
        self.emit_line("");
        self.emit_line("// Bit manipulation helpers");
        self.emit_line("function clz32(x) { return Math.clz32(x); }");
        self.emit_line("function ctz32(x) { return x === 0 ? 32 : 31 - Math.clz32(x & -x); }");
        self.emit_line("function popcnt32(x) { x = x - ((x >> 1) & 0x55555555); x = (x & 0x33333333) + ((x >> 2) & 0x33333333); return ((x + (x >> 4) & 0xF0F0F0F) * 0x1010101) >> 24; }");
        self.emit_line("function rotl32(x, k) { return (x << k) | (x >>> (32 - k)); }");
        self.emit_line("function rotr32(x, k) { return (x >>> k) | (x << (32 - k)); }");
        self.emit_line("function u32(x) { if (typeof x === 'bigint') return Number(BigInt.asUintN(32, x)); return x >>> 0; }");
    }

    fn emit_function_table(&mut self, module: &Module) {
        // Compute total table size from element segments
        let max_idx = module
            .elements
            .iter()
            .map(|e| e.offset + e.func_indices.len() as u32)
            .max()
            .unwrap_or(0);

        self.emit_line("// Function table (for call_indirect)");

        // Build a sparse table
        let mut table: Vec<Option<u32>> = vec![None; max_idx as usize];
        for seg in &module.elements {
            for (i, &func_idx) in seg.func_indices.iter().enumerate() {
                let idx = seg.offset as usize + i;
                if idx < table.len() {
                    table[idx] = Some(func_idx);
                }
            }
        }

        self.emit_line("const table = [");
        self.level += 1;
        for entry in &table {
            match entry {
                Some(func_idx) => {
                    let name = self.get_func_name(*func_idx);
                    self.emit_line(&format!("{},", name));
                }
                None => {
                    self.emit_line("null,");
                }
            }
        }
        self.level -= 1;
        self.emit_line("];");
    }

    fn emit_data_segment(&mut self, seg: &DataSegment) {
        use base64::Engine;
        let b64 = base64::engine::general_purpose::STANDARD.encode(&seg.data);
        // Split into lines of 76 chars for readability
        const LINE_LEN: usize = 76;
        if b64.len() <= LINE_LEN {
            self.emit_line(&format!(
                "buf.set(Uint8Array.from(atob(\"{}\"), c => c.charCodeAt(0)), {});",
                b64, seg.offset
            ));
        } else {
            self.emit_line(&format!("buf.set(Uint8Array.from(atob("));
            self.level += 1;
            let mut pos = 0;
            while pos < b64.len() {
                let end = (pos + LINE_LEN).min(b64.len());
                let chunk = &b64[pos..end];
                if end < b64.len() {
                    self.emit_line(&format!("\"{}\" +", chunk));
                } else {
                    self.emit_line(&format!("\"{}\"", chunk));
                }
                pos = end;
            }
            self.level -= 1;
            self.emit_line(&format!("), c => c.charCodeAt(0)), {});", seg.offset));
        }
    }

    fn emit_function(&mut self, func: &Function) {
        // Set param count for local variable naming
        self.current_param_count = func.params.len();

        let (name, original_name) = self.get_func_name_with_original(func.index);
        let params: Vec<String> = (0..func.params.len()).map(|i| format!("p{}", i)).collect();

        // Emit comment with original name if it differs
        if let Some(orig) = original_name {
            if orig != name {
                self.emit_line(&format!("// {}", orig));
            }
        }

        self.emit_line(&format!("function {}({}) {{", name, params.join(", ")));
        self.level += 1;

        // Declare locals
        let num_locals = func.locals.len();
        let mut local_decls: Vec<String> = func
            .locals
            .iter()
            .enumerate()
            .map(|(i, ty)| {
                let init = match ty {
                    ValType::I64 => " = 0n",
                    _ => " = 0",
                };
                format!("l{}{}", i, init)
            })
            .collect();

        // Also declare any temp locals introduced by the lifter (for saving locals before reassignment)
        let temp_locals = Self::collect_temp_locals(&func.body);
        for idx in &temp_locals {
            local_decls.push(self.local_name(*idx));
        }

        if !local_decls.is_empty() {
            self.emit_line(&format!("let {};", local_decls.join(", ")));
        }

        // Emit body
        self.emit_block(&func.body);

        self.level -= 1;
        self.emit_line("}");
    }

    fn emit_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.emit_stmt(stmt);
        }
    }

    /// Emit an expression in a boolean context (conditions)
    fn emit_expr_as_condition(&mut self, expr: &Expr) -> String {
        let prev = self.in_bool_context;
        self.in_bool_context = true;
        let result = self.emit_expr(expr);
        self.in_bool_context = prev;
        result
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::LocalSet { local, value } => {
                let val = self.emit_expr(value);
                let name = self.local_name(*local);
                self.emit_line(&format!("{} = {};", name, val));
            }

            Stmt::GlobalSet { global, value } => {
                let val = self.emit_expr(value);
                self.emit_line(&format!("g{} = {};", global, val));
            }

            Stmt::Store {
                addr,
                offset,
                value,
                size,
            } => {
                let addr_str = self.emit_expr(addr);
                let val_str = self.emit_expr(value);
                let func = match size {
                    MemSize::I8 => "store_i8",
                    MemSize::I16 => "store_i16",
                    MemSize::I32 => "store_i32",
                    MemSize::I64 => "store_i64",
                    MemSize::F32 => "store_f32",
                    MemSize::F64 => "store_f64",
                };
                if *offset == 0 {
                    self.emit_line(&format!("{}({}, {});", func, addr_str, val_str));
                } else {
                    self.emit_line(&format!("{}({}, {}, {});", func, addr_str, val_str, offset));
                }
            }

            Stmt::Expr(expr) => {
                let e = self.emit_expr(expr);
                // Only emit if it has side effects (calls)
                if matches!(
                    expr.kind,
                    ExprKind::Call { .. } | ExprKind::CallIndirect { .. }
                ) {
                    self.emit_line(&format!("{};", e));
                }
            }

            Stmt::Return(value) => {
                if let Some(val) = value {
                    let e = self.emit_expr(val);
                    self.emit_line(&format!("return {};", e));
                } else {
                    self.emit_line("return;");
                }
            }

            Stmt::If {
                cond,
                then_block,
                else_block,
            } => {
                let cond_str = self.emit_expr_as_condition(cond);
                self.emit_line(&format!("if ({}) {{", cond_str));
                self.level += 1;
                self.emit_block(then_block);
                self.level -= 1;
                if let Some(else_blk) = else_block {
                    self.emit_line("} else {");
                    self.level += 1;
                    self.emit_block(else_blk);
                    self.level -= 1;
                }
                self.emit_line("}");
            }

            Stmt::Block { label, body } => {
                self.emit_line(&format!("block_{}: {{", label));
                self.level += 1;
                self.emit_block(body);
                self.level -= 1;
                self.emit_line("}");
            }

            Stmt::Loop { label, body } => {
                self.emit_line(&format!("loop_{}: while (true) {{", label));
                self.level += 1;
                self.emit_block(body);
                // In WASM, falling through to the end of a loop exits it.
                // Always add break: block_terminates() can't account for
                // inner blocks exited via `break block_N`, which resume
                // at the end of the loop body. An unreachable break after
                // a truly terminating body is harmless.
                self.emit_line("break;");
                self.level -= 1;
                self.emit_line("}");
            }

            Stmt::DoWhile { body, cond } => {
                self.emit_line("do {");
                self.level += 1;
                self.emit_block(body);
                self.level -= 1;
                let cond_str = self.emit_expr_as_condition(cond);
                self.emit_line(&format!("}} while ({});", cond_str));
            }

            Stmt::While { cond, body } => {
                let cond_str = self.emit_expr_as_condition(cond);
                self.emit_line(&format!("while ({}) {{", cond_str));
                self.level += 1;
                self.emit_block(body);
                self.level -= 1;
                self.emit_line("}");
            }

            Stmt::Br { label, is_loop } => {
                if *is_loop {
                    if *label == u32::MAX {
                        self.emit_line("continue;");
                    } else {
                        self.emit_line(&format!("continue loop_{};", label));
                    }
                } else {
                    if *label == u32::MAX {
                        self.emit_line("break;");
                    } else {
                        self.emit_line(&format!("break block_{};", label));
                    }
                }
            }

            Stmt::BrIf {
                label,
                cond,
                is_loop,
            } => {
                let cond_str = self.emit_expr_as_condition(cond);
                if *is_loop {
                    if *label == u32::MAX {
                        self.emit_line(&format!("if ({}) continue;", cond_str));
                    } else {
                        self.emit_line(&format!("if ({}) continue loop_{};", cond_str, label));
                    }
                } else {
                    if *label == u32::MAX {
                        self.emit_line(&format!("if ({}) break;", cond_str));
                    } else {
                        self.emit_line(&format!("if ({}) break block_{};", cond_str, label));
                    }
                }
            }

            Stmt::BrTable {
                index,
                targets,
                default,
            } => {
                // Emit as if-else chain since JavaScript switch can't break to external labels
                let idx = self.emit_expr(index);

                for (i, target) in targets.iter().enumerate() {
                    let (kw, prefix) = if target.is_loop {
                        ("continue", "loop")
                    } else {
                        ("break", "block")
                    };

                    if i == 0 {
                        self.emit_line(&format!("if (({}) === {}) {{", idx, i));
                    } else {
                        self.emit_line(&format!("}} else if (({}) === {}) {{", idx, i));
                    }
                    self.level += 1;
                    self.emit_line(&format!("{} {}_{};", kw, prefix, target.label));
                    self.level -= 1;
                }

                // Default case
                let (kw, prefix) = if default.is_loop {
                    ("continue", "loop")
                } else {
                    ("break", "block")
                };

                if targets.is_empty() {
                    self.emit_line(&format!("{} {}_{};", kw, prefix, default.label));
                } else {
                    self.emit_line("} else {");
                    self.level += 1;
                    self.emit_line(&format!("{} {}_{};", kw, prefix, default.label));
                    self.level -= 1;
                    self.emit_line("}");
                }
            }

            Stmt::Unreachable => {
                self.emit_line("throw new Error('unreachable');");
            }

            Stmt::Nop => {
                // Don't emit anything for nop
            }

            Stmt::Drop(expr) => {
                let e = self.emit_expr(expr);
                // Only emit if it has side effects
                if matches!(
                    expr.kind,
                    ExprKind::Call { .. } | ExprKind::CallIndirect { .. }
                ) {
                    self.emit_line(&format!("{};", e));
                }
            }

            Stmt::Switch {
                index,
                cases,
                default,
            } => {
                let idx = self.emit_expr(index);
                self.emit_line(&format!("switch ({}) {{", idx));
                self.level += 1;
                for case in cases {
                    for val in &case.values {
                        self.emit_line(&format!("case {}:", val));
                    }
                    self.level += 1;
                    self.emit_block(&case.body);
                    if !block_terminates(&case.body) {
                        self.emit_line("break;");
                    }
                    self.level -= 1;
                }
                if let Some(def) = default {
                    self.emit_line("default:");
                    self.level += 1;
                    self.emit_block(def);
                    self.level -= 1;
                }
                self.level -= 1;
                self.emit_line("}");
            }

            Stmt::TryFinally {
                body,
                finally_block,
            } => {
                self.emit_line("try {");
                self.level += 1;
                self.emit_block(body);
                self.level -= 1;
                self.emit_line("} finally {");
                self.level += 1;
                self.emit_block(finally_block);
                self.level -= 1;
                self.emit_line("}");
            }
        }
    }

    fn emit_expr(&mut self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::I32Const(v) => format!("{}", v),
            ExprKind::I64Const(v) => format!("{}n", v),
            ExprKind::F32Const(v) => {
                if v.is_nan() {
                    "NaN".to_string()
                } else if v.is_infinite() {
                    if *v > 0.0 {
                        "Infinity".to_string()
                    } else {
                        "-Infinity".to_string()
                    }
                } else {
                    format!("{}", v)
                }
            }
            ExprKind::F64Const(v) => {
                if v.is_nan() {
                    "NaN".to_string()
                } else if v.is_infinite() {
                    if *v > 0.0 {
                        "Infinity".to_string()
                    } else {
                        "-Infinity".to_string()
                    }
                } else {
                    format!("{}", v)
                }
            }

            ExprKind::Local(idx) => self.local_name(*idx),
            ExprKind::Global(idx) => format!("g{}", idx),

            ExprKind::BinOp(op, a, b) => {
                // Convert "a + (-N)" to "a - N" for readability
                if matches!(op, BinOp::Add | BinOp::FAdd) {
                    if let Some(neg_val) = get_negative_const(&b.kind) {
                        let a_str = self.emit_expr(a);
                        return format!("({} - {})", a_str, neg_val);
                    }
                }
                let a_str = self.emit_expr(a);
                let b_str = self.emit_expr(b);
                self.emit_binop(*op, &a_str, &b_str, &expr.ty)
            }

            ExprKind::UnaryOp(op, a) => {
                let a_str = self.emit_expr(a);
                self.emit_unaryop(*op, &a_str, &expr.ty)
            }

            ExprKind::Compare(op, a, b, ref operand_ty) => {
                let a_str = self.emit_expr(a);
                let b_str = self.emit_expr(b);
                self.emit_cmpop(*op, &a_str, &b_str, operand_ty)
            }

            ExprKind::Load {
                addr,
                offset,
                size,
                signed,
            } => {
                let addr_str = self.emit_expr(addr);
                let func = match (size, signed) {
                    (MemSize::I8, true) => "load_i8",
                    (MemSize::I8, false) => "load_u8",
                    (MemSize::I16, true) => "load_i16",
                    (MemSize::I16, false) => "load_u16",
                    (MemSize::I32, _) => "load_i32",
                    (MemSize::I64, _) => "load_i64",
                    (MemSize::F32, _) => "load_f32",
                    (MemSize::F64, _) => "load_f64",
                };
                if *offset == 0 {
                    format!("{}({})", func, addr_str)
                } else {
                    format!("{}({}, {})", func, addr_str, offset)
                }
            }

            ExprKind::Call { func, args } => {
                // Handle special intrinsics
                if *func == u32::MAX {
                    return "memory.buffer.byteLength / 65536".to_string();
                }
                if *func == u32::MAX - 1 {
                    let arg = args.first().map(|a| self.emit_expr(a)).unwrap_or_default();
                    return format!("memory.grow({})", arg);
                }
                if *func == u32::MAX - 2 {
                    // memory.fill(dest, value, len)
                    let dest = args.get(0).map(|a| self.emit_expr(a)).unwrap_or_default();
                    let value = args.get(1).map(|a| self.emit_expr(a)).unwrap_or_default();
                    let len = args.get(2).map(|a| self.emit_expr(a)).unwrap_or_default();
                    return format!(
                        "new Uint8Array(memory.buffer).fill({}, {}, {} + {})",
                        value, dest, dest, len
                    );
                }
                if *func == u32::MAX - 3 {
                    // memory.copy(dest, src, len)
                    let dest = args.get(0).map(|a| self.emit_expr(a)).unwrap_or_default();
                    let src = args.get(1).map(|a| self.emit_expr(a)).unwrap_or_default();
                    let len = args.get(2).map(|a| self.emit_expr(a)).unwrap_or_default();
                    return format!(
                        "new Uint8Array(memory.buffer).copyWithin({}, {}, {} + {})",
                        dest, src, src, len
                    );
                }

                let name = self.get_func_name(*func);
                let args_str: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("{}({})", name, args_str.join(", "))
            }

            ExprKind::CallIndirect { index, args, .. } => {
                let idx = self.emit_expr(index);
                let args_str: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("table[{}]({})", idx, args_str.join(", "))
            }

            ExprKind::Select {
                cond,
                then_val,
                else_val,
            } => {
                let c = self.emit_expr(cond);
                let t = self.emit_expr(then_val);
                let e = self.emit_expr(else_val);
                format!("({} ? {} : {})", c, t, e)
            }

            ExprKind::Convert { op, expr } => {
                let e = self.emit_expr(expr);
                self.emit_convert(*op, &e)
            }

            // High-level expressions
            ExprKind::StringLiteral(s) => {
                format!("\"{}\"", escape_js_string(s))
            }

            ExprKind::GoString { ptr, len } => {
                let p = self.emit_expr(ptr);
                let l = self.emit_expr(len);
                format!("go_string({}, {})", p, l)
            }

            ExprKind::GoSlice { ptr, len, cap } => {
                let p = self.emit_expr(ptr);
                let l = self.emit_expr(len);
                let c = self.emit_expr(cap);
                format!("go_slice({}, {}, {})", p, l, c)
            }

            ExprKind::GoInterface { type_ptr, data } => {
                let t = self.emit_expr(type_ptr);
                let d = self.emit_expr(data);
                format!("go_interface({}, {})", t, d)
            }

            ExprKind::ResolvedPointer { addr, resolved } => {
                format!("{} /* \"{}\" */", addr, escape_js_string(resolved))
            }
        }
    }

    fn emit_binop(&mut self, op: BinOp, a: &str, b: &str, ty: &InferredType) -> String {
        let is_i64 = *ty == InferredType::I64;
        match op {
            BinOp::Add => {
                if is_i64 {
                    format!("BigInt.asIntN(64, {} + {})", a, b)
                } else {
                    format!("(({} + {}) | 0)", a, b)
                }
            }
            BinOp::Sub => {
                if is_i64 {
                    format!("BigInt.asIntN(64, {} - {})", a, b)
                } else {
                    format!("(({} - {}) | 0)", a, b)
                }
            }
            BinOp::Mul => {
                if is_i64 {
                    format!("BigInt.asIntN(64, {} * {})", a, b)
                } else {
                    format!("Math.imul({}, {})", a, b)
                }
            }
            BinOp::DivS => {
                if is_i64 {
                    format!("({} / {})", a, b)
                } else {
                    format!("({} / {}) | 0", a, b)
                }
            }
            BinOp::DivU => {
                if is_i64 {
                    format!(
                        "(BigInt.asUintN(64, BigInt({})) / BigInt.asUintN(64, BigInt({})))",
                        a, b
                    )
                } else {
                    format!("(u32({}) / u32({})) | 0", a, b)
                }
            }
            BinOp::RemS => format!("({} % {})", a, b),
            BinOp::RemU => {
                if is_i64 {
                    format!(
                        "(BigInt.asUintN(64, BigInt({})) % BigInt.asUintN(64, BigInt({})))",
                        a, b
                    )
                } else {
                    format!("(u32({}) % u32({}))", a, b)
                }
            }
            BinOp::And => format!("({} & {})", a, b),
            BinOp::Or => format!("({} | {})", a, b),
            BinOp::Xor => format!("({} ^ {})", a, b),
            BinOp::Shl => {
                if is_i64 {
                    format!("BigInt.asIntN(64, {} << {})", a, b)
                } else {
                    format!("({} << {})", a, b)
                }
            }
            BinOp::ShrS => format!("({} >> {})", a, b),
            BinOp::ShrU => {
                if is_i64 {
                    format!(
                        "BigInt.asIntN(64, BigInt.asUintN(64, BigInt({})) >> {})",
                        a, b
                    )
                } else {
                    format!("({} >>> {})", a, b)
                }
            }
            BinOp::Rotl => {
                if is_i64 {
                    format!("BigInt.asIntN(64, BigInt.asUintN(64, BigInt({a})) << ({b} & 63n) | BigInt.asUintN(64, BigInt({a})) >> (64n - ({b} & 63n)))", a = a, b = b)
                } else {
                    format!("rotl32({}, {})", a, b)
                }
            }
            BinOp::Rotr => {
                if is_i64 {
                    format!("BigInt.asIntN(64, BigInt.asUintN(64, BigInt({a})) >> ({b} & 63n) | BigInt.asUintN(64, BigInt({a})) << (64n - ({b} & 63n)))", a = a, b = b)
                } else {
                    format!("rotr32({}, {})", a, b)
                }
            }
            BinOp::FAdd => format!("({} + {})", a, b),
            BinOp::FSub => format!("({} - {})", a, b),
            BinOp::FMul => format!("({} * {})", a, b),
            BinOp::FDiv => format!("({} / {})", a, b),
            BinOp::FMin => format!("Math.min({}, {})", a, b),
            BinOp::FMax => format!("Math.max({}, {})", a, b),
            BinOp::FCopysign => format!("Math.sign({}) * Math.abs({})", b, a),
        }
    }

    fn emit_unaryop(&mut self, op: UnaryOp, a: &str, operand_ty: &InferredType) -> String {
        match op {
            UnaryOp::Clz => {
                if *operand_ty == InferredType::I64 {
                    format!("BigInt(Math.clz32(Number({} >> 32n))) + (({} >> 32n) === 0n ? BigInt(Math.clz32(Number({} & 0xFFFFFFFFn))) : 0n)", a, a, a)
                } else {
                    format!("clz32({})", a)
                }
            }
            UnaryOp::Ctz => {
                if *operand_ty == InferredType::I64 {
                    format!("(({} & 0xFFFFFFFFn) === 0n ? BigInt(ctz32(Number({} >> 32n))) + 32n : BigInt(ctz32(Number({} & 0xFFFFFFFFn))))", a, a, a)
                } else {
                    format!("ctz32({})", a)
                }
            }
            UnaryOp::Popcnt => {
                if *operand_ty == InferredType::I64 {
                    format!("BigInt(popcnt32(Number({} & 0xFFFFFFFFn)) + popcnt32(Number(({} >> 32n) & 0xFFFFFFFFn)))", a, a)
                } else {
                    format!("popcnt32({})", a)
                }
            }
            UnaryOp::Eqz => {
                let zero = if *operand_ty == InferredType::I64 {
                    "0n"
                } else {
                    "0"
                };
                if self.in_bool_context {
                    format!("({} === {})", a, zero)
                } else {
                    format!("(({} === {}) ? 1 : 0)", a, zero)
                }
            }
            UnaryOp::FAbs => format!("Math.abs({})", a),
            UnaryOp::FNeg => format!("(-{})", a),
            UnaryOp::FCeil => format!("Math.ceil({})", a),
            UnaryOp::FFloor => format!("Math.floor({})", a),
            UnaryOp::FTrunc => format!("Math.trunc({})", a),
            UnaryOp::FNearest => format!("Math.round({})", a),
            UnaryOp::FSqrt => format!("Math.sqrt({})", a),
        }
    }

    fn emit_cmpop(&mut self, op: CmpOp, a: &str, b: &str, operand_ty: &InferredType) -> String {
        let is_i64 = *operand_ty == InferredType::I64;
        let result = match op {
            CmpOp::Eq | CmpOp::FEq => format!("{} === {}", a, b),
            CmpOp::Ne | CmpOp::FNe => format!("{} !== {}", a, b),
            CmpOp::LtS | CmpOp::FLt => format!("{} < {}", a, b),
            CmpOp::LtU => {
                if is_i64 {
                    format!(
                        "BigInt.asUintN(64, BigInt({})) < BigInt.asUintN(64, BigInt({}))",
                        a, b
                    )
                } else {
                    format!("{} < {}", self.as_u32(a), self.as_u32(b))
                }
            }
            CmpOp::GtS | CmpOp::FGt => format!("{} > {}", a, b),
            CmpOp::GtU => {
                if is_i64 {
                    format!(
                        "BigInt.asUintN(64, BigInt({})) > BigInt.asUintN(64, BigInt({}))",
                        a, b
                    )
                } else {
                    format!("{} > {}", self.as_u32(a), self.as_u32(b))
                }
            }
            CmpOp::LeS | CmpOp::FLe => format!("{} <= {}", a, b),
            CmpOp::LeU => {
                if is_i64 {
                    format!(
                        "BigInt.asUintN(64, BigInt({})) <= BigInt.asUintN(64, BigInt({}))",
                        a, b
                    )
                } else {
                    format!("{} <= {}", self.as_u32(a), self.as_u32(b))
                }
            }
            CmpOp::GeS | CmpOp::FGe => format!("{} >= {}", a, b),
            CmpOp::GeU => {
                if is_i64 {
                    format!(
                        "BigInt.asUintN(64, BigInt({})) >= BigInt.asUintN(64, BigInt({}))",
                        a, b
                    )
                } else {
                    format!("{} >= {}", self.as_u32(a), self.as_u32(b))
                }
            }
        };
        if self.in_bool_context {
            result
        } else {
            format!("({} ? 1 : 0)", result)
        }
    }

    /// Wrap operand with u32() unless it's a non-negative integer literal
    fn as_u32(&self, s: &str) -> String {
        // Skip u32() for non-negative integer literals
        if s.chars().all(|c| c.is_ascii_digit()) {
            return s.to_string();
        }
        if let Ok(n) = s.parse::<i64>() {
            if n >= 0 && n <= u32::MAX as i64 {
                return s.to_string();
            }
        }
        let inner = strip_outer_parens(s);
        format!("u32({})", inner)
    }

    fn emit_convert(&mut self, op: ConvertOp, e: &str) -> String {
        match op {
            ConvertOp::I32WrapI64 => format!("Number(BigInt.asIntN(32, {}))", e),
            ConvertOp::I64ExtendI32S => format!("BigInt({})", e),
            ConvertOp::I64ExtendI32U => format!("BigInt(u32({}))", e),
            ConvertOp::I32TruncF32S | ConvertOp::I32TruncF64S => format!("Math.trunc({})", e),
            ConvertOp::I32TruncF32U | ConvertOp::I32TruncF64U => {
                format!("u32(Math.trunc({}))", e)
            }
            ConvertOp::I64TruncF32S | ConvertOp::I64TruncF64S => {
                format!("BigInt(Math.trunc({}))", e)
            }
            ConvertOp::I64TruncF32U | ConvertOp::I64TruncF64U => {
                format!("BigInt(Math.trunc({})) & 0xFFFFFFFFFFFFFFFFn", e)
            }
            ConvertOp::F32ConvertI32S
            | ConvertOp::F64ConvertI32S
            | ConvertOp::F32ConvertI64S
            | ConvertOp::F64ConvertI64S => format!("Number({})", e),
            ConvertOp::F32ConvertI32U | ConvertOp::F64ConvertI32U => format!("Number(u32({}))", e),
            ConvertOp::F32ConvertI64U | ConvertOp::F64ConvertI64U => {
                format!("Number(BigInt.asUintN(64, BigInt({})))", e)
            }
            ConvertOp::F32DemoteF64 => format!("Math.fround({})", e),
            ConvertOp::F64PromoteF32 => e.to_string(),
            ConvertOp::I32ReinterpretF32 => {
                format!("(new Int32Array(new Float32Array([{}]).buffer))[0]", e)
            }
            ConvertOp::I64ReinterpretF64 => {
                format!("(new BigInt64Array(new Float64Array([{}]).buffer))[0]", e)
            }
            ConvertOp::F32ReinterpretI32 => {
                format!("(new Float32Array(new Int32Array([{}]).buffer))[0]", e)
            }
            ConvertOp::F64ReinterpretI64 => {
                format!("(new Float64Array(new BigInt64Array([{}]).buffer))[0]", e)
            }
            ConvertOp::I32Extend8S => format!("({} << 24) >> 24", e),
            ConvertOp::I32Extend16S => format!("({} << 16) >> 16", e),
            ConvertOp::I64Extend8S => format!("BigInt.asIntN(8, {})", e),
            ConvertOp::I64Extend16S => format!("BigInt.asIntN(16, {})", e),
            ConvertOp::I64Extend32S => format!("BigInt.asIntN(32, {})", e),
            ConvertOp::I32TruncSatF32S | ConvertOp::I32TruncSatF64S => {
                format!("(Number.isNaN({0}) ? 0 : Math.min(Math.max(Math.trunc({0}), -2147483648), 2147483647))", e)
            }
            ConvertOp::I32TruncSatF32U | ConvertOp::I32TruncSatF64U => {
                format!("(Number.isNaN({0}) ? 0 : u32(Math.min(Math.max(Math.trunc({0}), 0), 4294967295)))", e)
            }
            ConvertOp::I64TruncSatF32S | ConvertOp::I64TruncSatF64S => {
                format!("(Number.isNaN({0}) ? 0n : BigInt(Math.min(Math.max(Math.trunc({0}), -9223372036854775808), 9223372036854775807)))", e)
            }
            ConvertOp::I64TruncSatF32U | ConvertOp::I64TruncSatF64U => {
                format!("(Number.isNaN({0}) ? 0n : BigInt(Math.min(Math.max(Math.trunc({0}), 0), 18446744073709551615)) & 0xFFFFFFFFFFFFFFFFn)", e)
            }
        }
    }

    fn local_name(&self, idx: u32) -> String {
        let idx = idx as usize;
        if idx < self.current_param_count {
            // It's a parameter
            format!("p{}", idx)
        } else {
            // It's a local variable
            format!("l{}", idx - self.current_param_count)
        }
    }

    /// Collect temp local indices (>= u32::MAX/2) used in LocalSet statements within a block
    fn collect_temp_locals(block: &crate::ir::Block) -> Vec<u32> {
        use std::collections::BTreeSet;
        let mut temps = BTreeSet::new();
        Self::collect_temp_locals_inner(&block.stmts, &mut temps);
        temps.into_iter().collect()
    }

    fn collect_temp_locals_inner(stmts: &[Stmt], temps: &mut std::collections::BTreeSet<u32>) {
        const TEMP_BASE: u32 = u32::MAX / 2;
        for stmt in stmts {
            match stmt {
                Stmt::LocalSet { local, .. } if *local >= TEMP_BASE => {
                    temps.insert(*local);
                }
                Stmt::If {
                    then_block,
                    else_block,
                    ..
                } => {
                    Self::collect_temp_locals_inner(&then_block.stmts, temps);
                    if let Some(eb) = else_block {
                        Self::collect_temp_locals_inner(&eb.stmts, temps);
                    }
                }
                Stmt::Block { body, .. } | Stmt::Loop { body, .. } => {
                    Self::collect_temp_locals_inner(&body.stmts, temps);
                }
                Stmt::DoWhile { body, .. } | Stmt::While { body, .. } => {
                    Self::collect_temp_locals_inner(&body.stmts, temps);
                }
                Stmt::Switch {
                    cases, default, ..
                } => {
                    for case in cases {
                        Self::collect_temp_locals_inner(&case.body.stmts, temps);
                    }
                    if let Some(def) = default {
                        Self::collect_temp_locals_inner(&def.stmts, temps);
                    }
                }
                Stmt::TryFinally {
                    body,
                    finally_block,
                } => {
                    Self::collect_temp_locals_inner(&body.stmts, temps);
                    Self::collect_temp_locals_inner(&finally_block.stmts, temps);
                }
                _ => {}
            }
        }
    }

    fn get_func_name(&self, idx: u32) -> String {
        let (name, _) = self.get_func_name_with_original(idx);
        name
    }

    /// Returns (sanitized_name, original_name) where original_name is Some if different
    fn get_func_name_with_original(&self, idx: u32) -> (String, Option<String>) {
        if let Some(module) = &self.module {
            // Check functions FIRST - func.name is already deduplicated in lift.rs
            for func in &module.functions {
                if func.index == idx {
                    if let Some(name) = &func.name {
                        let sanitized = sanitize_js_identifier(name);
                        let orig = if sanitized != *name {
                            Some(name.clone())
                        } else {
                            None
                        };
                        return (sanitized, orig);
                    }
                }
            }

            // Check if it's an import (imports don't go through lift_function)
            for (i, import) in module.imports.iter().enumerate() {
                if let ImportKind::Function(_) = import.kind {
                    if i as u32 == idx {
                        let original = format!("{}_{}", import.module, import.name);
                        let sanitized = sanitize_js_identifier(&original);
                        let orig = if sanitized != original {
                            Some(original)
                        } else {
                            None
                        };
                        return (sanitized, orig);
                    }
                }
            }

            // Fallback to exports if function has no name
            if let Some(name) = module.exports.get(&idx) {
                let sanitized = sanitize_js_identifier(name);
                let orig = if sanitized != *name {
                    Some(name.clone())
                } else {
                    None
                };
                return (sanitized, orig);
            }
        }

        (format!("func_{}", idx), None)
    }

    fn emit_exports(&mut self, module: &Module) {
        self.emit_line("// Exports (CommonJS)");
        self.emit_line("module.exports = {");
        self.level += 1;

        // Export runtime internals for testing
        self.emit_line("memory,");
        self.emit_line("get mem() { return mem(); },");
        if !module.globals.is_empty() {
            self.emit_line("globals,");
        }

        // Export imports object (so host can provide implementations)
        if !module.imports.is_empty() {
            self.emit_line("imports,");
        }

        // Export WASM exports
        for (idx, name) in &module.exports {
            let func_name = self.get_func_name(*idx);
            self.emit_line(&format!("{}: {},", name, func_name));
        }

        self.level -= 1;
        self.emit_line("};");
    }

    fn emit_line(&mut self, line: &str) {
        for _ in 0..self.level {
            self.output.push_str(&self.indent);
        }
        self.output.push_str(line);
        self.output.push('\n');
    }
}

impl Default for JsEmitter {
    fn default() -> Self {
        Self::new()
    }
}

/// Check if a block ends with a terminating statement (return, break, continue, unreachable)
fn block_terminates(block: &Block) -> bool {
    match block.stmts.last() {
        Some(Stmt::Return(_)) => true,
        Some(Stmt::Br { .. }) => true,
        Some(Stmt::BrIf { .. }) => false, // conditional, so doesn't always terminate
        Some(Stmt::BrTable { .. }) => true, // always branches somewhere
        Some(Stmt::Unreachable) => true,
        Some(Stmt::If {
            then_block,
            else_block,
            ..
        }) => {
            // Only terminates if BOTH branches terminate
            block_terminates(then_block) && else_block.as_ref().map_or(false, block_terminates)
        }
        Some(Stmt::Block { body, .. }) => block_terminates(body),
        Some(Stmt::Loop { body, .. }) => block_terminates(body),
        Some(Stmt::DoWhile { body, .. }) => block_terminates(body),
        Some(Stmt::While { body, .. }) => block_terminates(body),
        _ => false,
    }
}

/// Check if expression is a negative constant, return absolute value as string
/// E.g. -5 -> "5"
fn get_negative_const(kind: &ExprKind) -> Option<String> {
    match kind {
        ExprKind::I32Const(v) if *v < 0 => Some(format!("{}", v.wrapping_neg())),
        ExprKind::I64Const(v) if *v < 0 => Some(format!("{}n", v.wrapping_neg())),
        ExprKind::F32Const(v) if *v < 0.0 => Some(format!("{}", -v)),
        ExprKind::F64Const(v) if *v < 0.0 => Some(format!("{}", -v)),
        _ => None,
    }
}

/// Strip outer parentheses if they wrap the entire expression
fn strip_outer_parens(s: &str) -> &str {
    if s.starts_with('(') && s.ends_with(')') {
        // Verify parens are matching (not like "(a) + (b)")
        let inner = &s[1..s.len() - 1];
        let mut depth = 0;
        for c in inner.chars() {
            match c {
                '(' => depth += 1,
                ')' => {
                    if depth == 0 {
                        return s;
                    }
                    depth -= 1;
                }
                _ => {}
            }
        }
        if depth == 0 {
            return inner;
        }
    }
    s
}

/// Escape a string for JavaScript
fn escape_js_string(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            c if c.is_control() => {
                write!(result, "\\x{:02x}", c as u32).unwrap();
            }
            c => result.push(c),
        }
    }
    result
}
